apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qfz00yakp-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qfz00yakp-java-quarkus-gitops